### ISSUE TITLE
Problem with shouting

### ISSUE THREAD

**Issue by ScaredDonut** [martec/Miuna-Shoutbox-Client#7]
Hey,

I am having a problem when I am trying to post a shout, when I press [ENTER] it just creates a new line. I made the server and all, but it does not seem to work.

The URL is: http://lgbteens.net/index.php

Thanks for your time, and help.

**Comment by martec** [comment]
sorry...
i checked here and this plugin is incompatible with mybb 1.8.5.
mybb 1.8.5 using sceditor 1.4.7... and mybb 1.8.4 use sceditor 1.4.5... so this plugin is incompatible with sceditor 1.4.7... i will need release new version compatible with sceditor 1.4.7
so sorry, but unfortunately you have to wait until new update for this to work with MyBB 1.8.5...

**Comment by faerulsalamun** [comment]
Don't know this good solution or not but you can try.

Open folder jscript > miuna > shoutbox > miunashout.helper.js

Search text if(e.which == 13)  and change to if(e.originalEvent.which == 13) 

And minify code from miunashout.helper.js and copy to miunashout.helper.min.js

**Comment by martec** [comment]
issue solved in 3.0
http://community.mybb.com/thread-166773-post-1162161.html#pid1162161
