### ISSUE TITLE
Forbidden

### ISSUE THREAD

**Issue by PaulyJ1** [martec/Miuna-Shoutbox-Client#8]
Hello, I am trying to setup miuna shoutbox, I have done everything I need to do, but when I configure in ACP, I get this message: http://gyazo.com/a46a1555db2379266d10394c0b39fc28 any help?

**Comment by martec** [comment]
i believe that this is only coincidence....
this plugin not change anything related with server configuration. ex: chmod etc...

**Comment by PaulyJ1** [comment]
I am running MyBB 1.8.4 but everytime I try, this still happens?

**Comment by martec** [comment]
but what relation with this plugin and forbidden message to access /admin/index.php ?
for me only coincidence. and some misconfiguration with your host.
