### ISSUE TITLE
Could you install it for me for $$?

### ISSUE THREAD

**Issue by LallierQc** [martec/Miuna-Shoutbox-Client#9]
I had it installed before and it was working fine now I retried like 6 times and it's still not working.. It's just in the state where the buttons arent there and when you type and press enter it just goes to the other line . It's like if it's not connected correctly. I'm ready to pay 5$ if you can install it for me i'll give you my mybb pass so you can connect and you'll install it maybe? Because I want your shoutbox so bad it's perfect but damn I don't know what I'm doing wrong. you can add me on skype live:lalliergui or steam /id/buzzace

**Comment by martec** [comment]
so plz send admin test account, openshift account, cpanel account to check error log and ftp account to i can made change. Send this information in private forum of my test forum https://martec.ml/test/index.php ( Support of Miuna Shoutbox folder)
user: test pass: test123
Ps. You need create account, but not need activation. Plz create account with same nick used here.
Ps2. Not need pay.

**Comment by LallierQc** [comment]
Ok http://forum.electronic-game.com
Test user
Username : test
pass : testuser123
CPANEL
https://server1.nebulahosts.com:2083/
user : electronicgame
pass : eg777skateboard123 (i changed it for you thats not my pass lol)
openshit
user : glallier@live.ca
pass : eg777skateboard123
ftp 
host : 168.235.78.187
user : electronicgame
pass : eg777skateboard123

**Comment by LallierQc** [comment]
oops i snet it on your site

**Comment by martec** [comment]
plz read more careful send in Support of Miuna Shoutbox folder (create thread inside of folder). Not send PM, and not send this type of information here (security reason).

**Comment by martec** [comment]
i will close this, any questions ask in Support of Miuna Shoutbox folder in https://martec.ml/test/
